# Site settings
title: Hello Friends
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/clean" # the subpath of your site, e.g. /blog/
url: "https://Newyee1994.github.io" # the base hostname & protocol for your site
twitter_username: Newyee
github_username:  Newyee1994

# Build settings
markdown: kramdown
